[project]
name = "parsing-xxx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.12.15",
    "bs4>=0.0.2",
    "lxml>=6.0.0",
]
